### ISSUE TITLE
Doesn't work for version 9.8.4.2 

### ISSUE THREAD

**Issue by DineshSolanki** [grandprixgp/NoProcessLassoNag#1]

**Comment by grandprixgp** [comment]
Correct this is not actively maintained as I found Process Lasso would regularly be updated and simply stopped going through with updates. If I have time this weekend I will take a look.

**Comment by DineshSolanki** [comment]
Ok, take your time, also you may want to mention in Readme that it's not actively maintained so that someone who's willing to contribute can get a hint

**Comment by grandprixgp** [comment]
Updated to work on the latest version, added note regarding maintenance on readme. Thanks for the issue 👍

**Comment by DineshSolanki** [comment]
@grandprixgp you're awesome, thanks for the update.

**Comment by grandprixgp** [comment]
Updated again should require less maintenance now :)
